### PR TITLE
add remark-copy-linked-files plugin

### PR DESCRIPTION
**Pull request by sparky005**
adds plugin that allows for easy downloading of files linked in markdown posts

### CODE REVIEW

**Comment by wangonya** [comment]
Should the linked file be downloaded or opened when clicked? I was expecting a download dialogue but it just opened on the browser.

Using firefox on mac.

**Comment by wangonya** [comment]
Same behavior on chrome

**Comment by sparky005** [comment]
Ah, maybe a `.txt` file was a bad example. Since the browser knows how to open a `.txt` file, it'll just open it, instead of prompting you to download it. You can right click > Save File As to download in Firefox, and Chrome should have a similar function as well.

We can either leave the example as-is or we can remove the `.txt` extension, which will force the browser to download the file (tested in both Firefox and Chrome.) Your call, I don't mind either way!

**Comment by wangonya** [comment]
I've removed the `.txt` extension on the file but it still opens when clicked. I think a file format that prompts a download would be better suited to demo this feature. Could you try compressing the hello_world file into a zip and linking to that?

**Comment by sparky005** [comment]
Good thinking @wangonya. I've changed the file to a .zip and it's working on my machine with Firefox and Chrome. Sorry for the trouble here!

**Comment by wangonya** [comment]
Nice! It's working for me too.

Thanks, I really appreciate your input.

**Pull request merged**
